# Generated by Django 5.2 on 2025-06-04 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("creator_project", "0001_initial"),
        ("creator_subproject", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_reviewed", models.DateTimeField(auto_now_add=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("comments", models.TextField(blank=True)),
                (
                    "technical_score",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="امتیاز فنی (0-100)"
                    ),
                ),
                (
                    "financial_score",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="امتیاز مالی (0-100)"
                    ),
                ),
                (
                    "schedule_score",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="امتیاز زمان\u200cبندی (0-100)"
                    ),
                ),
                (
                    "scope_score",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="امتیاز محدوده (0-100)"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_reviews",
                        to="creator_project.project",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_project_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "بررسی پروژه",
                "verbose_name_plural": "بررسی\u200cهای پروژه",
                "ordering": ["-date_reviewed"],
            },
        ),
        migrations.CreateModel(
            name="SubProjectReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_reviewed", models.DateTimeField(auto_now_add=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("comments", models.TextField(blank=True)),
                (
                    "technical_score",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="امتیاز فنی (0-100)"
                    ),
                ),
                (
                    "financial_score",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="امتیاز مالی (0-100)"
                    ),
                ),
                (
                    "schedule_score",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="امتیاز زمان\u200cبندی (0-100)"
                    ),
                ),
                (
                    "execution_score",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="امتیاز اجرایی (0-100)"
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_subproject_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subproject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_reviews",
                        to="creator_subproject.subproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "بررسی زیرپروژه",
                "verbose_name_plural": "بررسی\u200cهای زیرپروژه",
                "ordering": ["-date_reviewed"],
            },
        ),
    ]
