#!/bin/bash
# Quick fix script to update migration file on server

cd ~/public_html/PMD/ProjectManagerDashboard/creator_program/migrations

# Backup original
cp 0002_program_province.py 0002_program_province.py.bak

# Create fixed version
cat > 0002_program_province.py << 'PYTHON_EOF'
# Generated by Django 5.2.4 on 2025-07-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_program', '0001_add_program_id_field'),
    ]

    operations = [
        # Add field without default to avoid MySQL strict mode error
        migrations.AddField(
            model_name='program',
            name='province',
            field=models.CharField(
                choices=[
                    ('البرز', 'البرز'), ('آذربایجان شرقی', 'آذربایجان شرقی'), ('آذربایجان غربی', 'آذربایجان غربی'),
                    ('بوشهر', 'بوشهر'), ('چهارمحال و بختیاری', 'چهارمحال و بختیاری'), ('فارس', 'فارس'),
                    ('گیلان', 'گیلان'), ('گلستان', 'گلستان'), ('همدان', 'همدان'), ('هرمزگان', 'هرمزگان'),
                    ('ایلام', 'ایلام'), ('اصفهان', 'اصفهان'), ('کرمان', 'کرمان'), ('کرمانشاه', 'کرمانشاه'),
                    ('خراسان شمالی', 'خراسان شمالی'), ('خراسان رضوی', 'خراسان رضوی'), ('خراسان جنوبی', 'خراسان جنوبی'),
                    ('خوزستان', 'خوزستان'), ('کهگیلویه و بویراحمد', 'کهگیلویه و بویراحمد'), ('کردستان', 'کردستان'),
                    ('لرستان', 'لرستان'), ('مرکزی', 'مرکزی'), ('مازندران', 'مازندران'), ('قزوین', 'قزوین'),
                    ('قم', 'قم'), ('سمنان', 'سمنان'), ('سیستان و بلوچستان', 'سیستان و بلوچستان'), ('تهران', 'تهران'),
                    ('یزد', 'یزد'), ('زنجان', 'زنجان'), ('کیش', 'کیش'), ('اردبیل', 'اردبیل')
                ],
                max_length=50,
                verbose_name='استان',
                null=True,
                blank=True,
            ),
        ),
        # Set default value for existing rows using raw SQL
        migrations.RunSQL(
            sql="UPDATE creator_program_program SET province = 'تهران' WHERE province IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Now make it non-nullable with default
        migrations.AlterField(
            model_name='program',
            name='province',
            field=models.CharField(
                choices=[
                    ('البرز', 'البرز'), ('آذربایجان شرقی', 'آذربایجان شرقی'), ('آذربایجان غربی', 'آذربایجان غربی'),
                    ('بوشهر', 'بوشهر'), ('چهارمحال و بختیاری', 'چهارمحال و بختیاری'), ('فارس', 'فارس'),
                    ('گیلان', 'گیلان'), ('گلستان', 'گلستان'), ('همدان', 'همدان'), ('هرمزگان', 'هرمزگان'),
                    ('ایلام', 'ایلام'), ('اصفهان', 'اصفهان'), ('کرمان', 'کرمان'), ('کرمانشاه', 'کرمانشاه'),
                    ('خراسان شمالی', 'خراسان شمالی'), ('خراسان رضوی', 'خراسان رضوی'), ('خراسان جنوبی', 'خراسان جنوبی'),
                    ('خوزستان', 'خوزستان'), ('کهگیلویه و بویراحمد', 'کهگیلویه و بویراحمد'), ('کردستان', 'کردستان'),
                    ('لرستان', 'لرستان'), ('مرکزی', 'مرکزی'), ('مازندران', 'مازندران'), ('قزوین', 'قزوین'),
                    ('قم', 'قم'), ('سمنان', 'سمنان'), ('سیستان و بلوچستان', 'سیستان و بلوچستان'), ('تهران', 'تهران'),
                    ('یزد', 'یزد'), ('زنجان', 'زنجان'), ('کیش', 'کیش'), ('اردبیل', 'اردبیل')
                ],
                default='تهران',
                max_length=50,
                verbose_name='استان',
            ),
        ),
    ]
PYTHON_EOF

echo "✅ Migration file updated!"
echo "Now run: python manage.py migrate"

