# Generated by Django 5.2.4 on 2025-07-31 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان طرح')),
                ('program_id', models.CharField(blank=True, max_length=50, unique=True, verbose_name='کد طرح')),
                ('program_type', models.CharField(choices=[('پایگاه امداد جادهای', 'پایگاه امداد جادهای'), ('پایگاه امداد کوهستانی', 'پایگاه امداد کوهستانی'), ('پایگاه امداد دریایی', 'پایگاه امداد دریایی'), ('ساختمان اداری آموزشی درمانی وفرهنگی', 'ساختمان اداری آموزشی درمانی وفرهنگی'), ('پایگاه عملیات پشتیبانی اقماری هوایی', 'پایگاه عملیات پشتیبانی اقماری هوایی'), ('مولد سازی', 'مولد سازی')], max_length=50, verbose_name='نوع طرح')),
                ('license_state', models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد'), ('دردست اقدام', 'دردست اقدام'), ('قبل از بخش نامه اردیبهشت 91', 'قبل از بخش نامه اردیبهشت 91')], max_length=50, verbose_name='وضعیت مجوز دفترچه توجیهی')),
                ('license_code', models.CharField(max_length=25, verbose_name='کد مجوز دفترچه توجیهی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='ارسال شده')),
                ('is_expert_approved', models.BooleanField(default=False, verbose_name='تایید کارشناس')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_programs', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'طرح',
                'verbose_name_plural': 'طرح\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramRejectionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_rejection_comments', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_comments', to='creator_program.program')),
            ],
            options={
                'verbose_name': 'نظر رد طرح',
                'verbose_name_plural': 'نظرات رد طرح',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_history', to='creator_program.program')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تاریخچه بروزرسانی طرح',
                'verbose_name_plural': 'تاریخچه بروزرسانی طرح\u200cها',
                'ordering': ['-updated_at'],
            },
        ),
    ]
