# Fixed migration that handles existing column
# Generated by Django 5.2.4 on 2025-07-31 11:39

from django.db import migrations, models


def check_and_fix_province_column(apps, schema_editor):
    """Check if column exists and fix it if needed"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'creator_program_program' 
            AND COLUMN_NAME = 'province'
        """)
        exists = cursor.fetchone()[0] > 0
        
        if exists:
            # Column exists, just update it
            cursor.execute("UPDATE creator_program_program SET province = 'تهران' WHERE province IS NULL;")
            cursor.execute("ALTER TABLE creator_program_program MODIFY COLUMN province VARCHAR(50) NOT NULL DEFAULT 'تهران';")
        else:
            # Column doesn't exist, add it
            cursor.execute("""
                ALTER TABLE creator_program_program 
                ADD COLUMN province VARCHAR(50) NULL;
            """)
            cursor.execute("UPDATE creator_program_program SET province = 'تهران' WHERE province IS NULL;")
            cursor.execute("ALTER TABLE creator_program_program MODIFY COLUMN province VARCHAR(50) NOT NULL DEFAULT 'تهران';")


class Migration(migrations.Migration):

    dependencies = [
        ('creator_program', '0001_add_program_id_field'),
    ]

    operations = [
        migrations.RunPython(
            check_and_fix_province_column,
            reverse_code=migrations.RunPython.noop,
        ),
        # Update Django's model state
        migrations.AlterField(
            model_name='program',
            name='province',
            field=models.CharField(
                choices=[
                    ('البرز', 'البرز'), ('آذربایجان شرقی', 'آذربایجان شرقی'), ('آذربایجان غربی', 'آذربایجان غربی'),
                    ('بوشهر', 'بوشهر'), ('چهارمحال و بختیاری', 'چهارمحال و بختیاری'), ('فارس', 'فارس'),
                    ('گیلان', 'گیلان'), ('گلستان', 'گلستان'), ('همدان', 'همدان'), ('هرمزگان', 'هرمزگان'),
                    ('ایلام', 'ایلام'), ('اصفهان', 'اصفهان'), ('کرمان', 'کرمان'), ('کرمانشاه', 'کرمانشاه'),
                    ('خراسان شمالی', 'خراسان شمالی'), ('خراسان رضوی', 'خراسان رضوی'), ('خراسان جنوبی', 'خراسان جنوبی'),
                    ('خوزستان', 'خوزستان'), ('کهگیلویه و بویراحمد', 'کهگیلویه و بویراحمد'), ('کردستان', 'کردستان'),
                    ('لرستان', 'لرستان'), ('مرکزی', 'مرکزی'), ('مازندران', 'مازندران'), ('قزوین', 'قزوین'),
                    ('قم', 'قم'), ('سمنان', 'سمنان'), ('سیستان و بلوچستان', 'سیستان و بلوچستان'), ('تهران', 'تهران'),
                    ('یزد', 'یزد'), ('زنجان', 'زنجان'), ('کیش', 'کیش'), ('اردبیل', 'اردبیل')
                ],
                default='تهران',
                max_length=50,
                verbose_name='استان',
            ),
        ),
    ]

