# Generated by Django 5.2.4 on 2025-07-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_program', '0002_program_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر'),
        ),
    ]
