# Generated by Django 5.2.4 on 2025-08-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_program', '0004_program_address_program_latitude_program_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_opening_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ افتتاح طرح'),
        ),
    ] 