# Generated by Django 5.2 on 2025-08-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creator_program", "0005_program_opening_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="program_type",
            field=models.CharField(
                choices=[
                    ("پایگاه امداد جاده ای", "پایگاه امداد جاده ای"),
                    ("پایگاه امداد کوهستانی", "پایگاه امداد کوهستانی"),
                    ("پایگاه امداد دریایی", "پایگاه امداد دریایی"),
                    (
                        "ساختمان اداری آموزشی درمانی وفرهنگی",
                        "ساختمان اداری آموزشی درمانی وفرهنگی",
                    ),
                    (
                        "پایگاه عملیات پشتیبانی اقماری هوایی",
                        "پایگاه عملیات پشتیبانی اقماری هوایی",
                    ),
                    ("مولد سازی", "مولد سازی"),
                    ("سالن چند منظوره/انبار امدادی", "سالن چند منظوره/انبار امدادی"),
                ],
                max_length=50,
                verbose_name="نوع طرح",
            ),
        ),
    ]
