# Generated by Django 5.2 on 2025-06-04 22:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "project_id",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("پایگاه امداد جادهای", "پایگاه امداد جادهای"),
                            ("پایگاه امداد کوهستانی", "پایگاه امداد کوهستانی"),
                            ("پایگاه امداد دریایی", "پایگاه امداد دریایی"),
                            (
                                "ساختمان اداری آموزشی درمانی وفرهنگی",
                                "ساختمان اداری آموزشی درمانی وفرهنگی",
                            ),
                            (
                                "پایگاه عملیات پشتیبانی اقماری هوایی",
                                "پایگاه عملیات پشتیبانی اقماری هوایی",
                            ),
                            ("مولد سازی", "مولد سازی"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("البرز", "البرز"),
                            ("آذربایجان شرقی", "آذربایجان شرقی"),
                            ("آذربایجان غربی", "آذربایجان غربی"),
                            ("بوشهر", "بوشهر"),
                            ("چهارمحال و بختیاری", "چهارمحال و بختیاری"),
                            ("فارس", "فارس"),
                            ("گیلان", "گیلان"),
                            ("گلستان", "گلستان"),
                            ("همدان", "همدان"),
                            ("هرمزگان", "هرمزگان"),
                            ("ایلام", "ایلام"),
                            ("اصفهان", "اصفهان"),
                            ("کرمان", "کرمان"),
                            ("کرمانشاه", "کرمانشاه"),
                            ("خراسان شمالی", "خراسان شمالی"),
                            ("خراسان رضوی", "خراسان رضوی"),
                            ("خراسان جنوبی", "خراسان جنوبی"),
                            ("خوزستان", "خوزستان"),
                            ("کهگیلویه و بویراحمد", "کهگیلویه و بویراحمد"),
                            ("کردستان", "کردستان"),
                            ("لرستان", "لرستان"),
                            ("مرکزی", "مرکزی"),
                            ("مازندران", "مازندران"),
                            ("قزوین", "قزوین"),
                            ("قم", "قم"),
                            ("سمنان", "سمنان"),
                            ("سیستان و بلوچستان", "سیستان و بلوچستان"),
                            ("تهران", "تهران"),
                            ("یزد", "یزد"),
                            ("زنجان", "زنجان"),
                            ("کیش", "کیش"),
                            ("اردبیل", "اردبیل"),
                        ],
                        max_length=50,
                    ),
                ),
                ("city", models.CharField(max_length=50)),
                ("address", models.TextField()),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="طول جغرافیایی",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="عرض جغرافیایی",
                    ),
                ),
                (
                    "area_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="عرصه",
                    ),
                ),
                (
                    "notables",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="اعیان",
                    ),
                ),
                (
                    "floor",
                    models.IntegerField(blank=True, null=True, verbose_name="طبقه"),
                ),
                (
                    "license_state",
                    models.CharField(
                        choices=[
                            ("دارد", "دارد"),
                            ("ندارد", "ندارد"),
                            ("دردست اقدام", "دردست اقدام"),
                            (
                                "قبل از بخش نامه اردیبهشت 91",
                                "قبل از بخش نامه اردیبهشت 91",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("license_code", models.CharField(max_length=25)),
                (
                    "physical_progress",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "estimated_opening_time",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ پایان پروژه"
                    ),
                ),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("فعال", "فعال"),
                            ("تامین اعتبار", "تامین اعتبار"),
                            ("غیره فعال", "غیره فعال"),
                        ],
                        default="غیره فعال",
                        max_length=50,
                        verbose_name="وضعیت کلی",
                    ),
                ),
                (
                    "allocation_credit_cash_national",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "allocation_credit_cash_province",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "allocation_credit_cash_charity",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "allocation_credit_cash_travel",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "allocation_credit_treasury_national",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "allocation_credit_treasury_province",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "allocation_credit_treasury_travel",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "debt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "cached_total_debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="مجموع دیون",
                    ),
                ),
                (
                    "cached_required_credit_contracts",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="اعتبار مورد نیاز تکمیل قرار داد ها",
                    ),
                ),
                (
                    "cached_required_credit_project",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="اعتبار مورد نیاز تکمیل پروژه",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "is_submitted",
                    models.BooleanField(default=False, verbose_name="ارسال شده"),
                ),
                (
                    "is_expert_approved",
                    models.BooleanField(default=False, verbose_name="تایید کارشناس"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پروژه",
                "verbose_name_plural": "پروژه\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FundingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "province_suggested_amount",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="مبلغ پیشنهادی توسط استان",
                        max_digits=15,
                        verbose_name="مبلغ پیشنهادی استان",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("خیلی زیاد", "خیلی زیاد"),
                            ("زیاد", "زیاد"),
                            ("متوسط", "متوسط"),
                            ("کم", "کم"),
                            ("خیلی کم", "خیلی کم"),
                        ],
                        help_text="میزان اولویت درخواست",
                        max_length=20,
                        verbose_name="اولویت",
                    ),
                ),
                (
                    "province_description",
                    models.TextField(
                        help_text="توضیحات تکمیلی استان", verbose_name="توضیحات استان"
                    ),
                ),
                (
                    "headquarters_suggested_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="مبلغ پیشنهادی توسط کارشناس ستاد",
                        max_digits=15,
                        null=True,
                        verbose_name="مبلغ پیشنهادی ستاد",
                    ),
                ),
                (
                    "expert_description",
                    models.TextField(
                        blank=True,
                        help_text="توضیحات تکمیلی کارشناس",
                        verbose_name="توضیحات کارشناس",
                    ),
                ),
                (
                    "expert_rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="دلیل رد درخواست توسط کارشناس",
                        verbose_name="دلیل رد توسط کارشناس",
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="مبلغ نهایی مصوب",
                        max_digits=15,
                        null=True,
                        verbose_name="مبلغ نهایی",
                    ),
                ),
                (
                    "chief_rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="دلیل رد درخواست توسط رئیس",
                        verbose_name="دلیل رد توسط رئیس",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("پیش\u200cنویس", "پیش\u200cنویس"),
                            ("ارسال شده به کارشناس", "ارسال شده به کارشناس"),
                            ("رد شده توسط کارشناس", "رد شده توسط کارشناس"),
                            ("تایید شده توسط کارشناس", "تایید شده توسط کارشناس"),
                            ("ارسال شده به رئیس", "ارسال شده به رئیس"),
                            ("رد شده توسط رئیس", "رد شده توسط رئیس"),
                            ("تایید شده", "تایید شده"),
                            ("در تاریخچه", "در تاریخچه"),
                        ],
                        default="پیش\u200cنویس",
                        max_length=50,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ ارسال"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ تایید"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ آرشیو"
                    ),
                ),
                (
                    "chief_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_funding_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="رئیس بررسی کننده",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_funding_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجاد کننده",
                    ),
                ),
                (
                    "expert_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_funding_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کارشناس بررسی کننده",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_requests",
                        to="creator_project.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست اعتبار",
                "verbose_name_plural": "درخواست\u200cهای اعتبار",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AllocationCreditTreasury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ملی", "ملی"),
                            ("استانی", "استانی"),
                            ("مصوبات سفر", "مصوبات سفر"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_added", models.DateField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treasury_allocations",
                        to="creator_project.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AllocationCreditCash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ملی", "ملی"),
                            ("استانی", "استانی"),
                            ("مصوبات سفر", "مصوبات سفر"),
                            ("درآمد مرکز", "درآمد مرکز"),
                            ("خیرساز", "خیرساز"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_added", models.DateField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_allocations",
                        to="creator_project.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ALL_Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("province", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("project_type", models.CharField(max_length=50)),
                (
                    "physical_progress",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total_allocation_cash",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "total_allocation_treasury",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                ("created_by", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField()),
                ("is_approved", models.BooleanField(default=False)),
                ("subproject_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="creator_project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "خلاصه پروژه",
                "verbose_name_plural": "خلاصه پروژه\u200cها",
            },
        ),
        migrations.CreateModel(
            name="ProjectFinancialAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="مبلغ"
                    ),
                ),
                (
                    "letter_number",
                    models.CharField(max_length=100, verbose_name="شماره نامه"),
                ),
                (
                    "allocation_type",
                    models.CharField(
                        choices=[
                            ("اعتبار نقدی-ملی", "اعتبار نقدی-ملی"),
                            ("اعتبار نقدی-استانی", "اعتبار نقدی-استانی"),
                            ("اعتبار نقدی-سفر", "اعتبار نقدی-سفر"),
                            ("اعتبار اسناد خزانه-ملی", "اعتبار اسناد خزانه-ملی"),
                            ("اعتبار اسناد خزانه-استانی", "اعتبار اسناد خزانه-استانی"),
                            ("اعتبار اسناد خزانه-سفر", "اعتبار اسناد خزانه-سفر"),
                            ("نقدی- خییر", "نقدی- خییر"),
                        ],
                        max_length=50,
                        verbose_name="نوع تخصیص",
                    ),
                ),
                (
                    "allocation_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاریخ تخصیص"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="creator_project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "تخصیص مالی پروژه",
                "verbose_name_plural": "تخصیص\u200cهای مالی پروژه",
                "ordering": ["-allocation_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectRejectionComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_rejection_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rejection_comments",
                        to="creator_project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "نظر رد پروژه",
                "verbose_name_plural": "نظرات رد پروژه",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectUpdateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("field_name", models.CharField(max_length=50)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_history",
                        to="creator_project.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تاریخچه بروزرسانی پروژه",
                "verbose_name_plural": "تاریخچه بروزرسانی پروژه\u200cها",
                "ordering": ["-updated_at"],
            },
        ),
    ]
