# Generated by Django 5.2.4 on 2025-07-31 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_program', '0001_add_program_id_field'),
        ('creator_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='license_code',
        ),
        migrations.RemoveField(
            model_name='project',
            name='license_state',
        ),
        migrations.AddField(
            model_name='project',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='creator_program.program', verbose_name='طرح'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('احداث', 'احداث'), ('تکمیل', 'تکمیل'), ('محوطه سازی', 'محوطه سازی'), ('دیوار کشی', 'دیوار کشی'), ('محوطه سازی و دیوار کشی', 'محوطه سازی و دیوار کشی'), ('تعمیرات', 'تعمیرات'), ('مشاور فاز یک و دو (طراحی)', 'مشاور فاز یک و دو (طراحی)'), ('مشاور فاز سه (نظارت)', 'مشاور فاز سه (نظارت)')], max_length=50, verbose_name='نوع پروژه'),
        ),
    ]
