# Generated by Django 5.2.4 on 2025-07-31 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator_project', '0002_add_program_id_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='address',
        ),
    ]
