# Generated by Django 5.2.4 on 2025-08-01 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator_project', '0003_remove_project_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='project',
            name='longitude',
        ),
    ]
