# Generated by Django 5.2 on 2025-08-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creator_project", "0004_remove_project_latitude_remove_project_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="site_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="مساحت محوطه سازی",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="wall_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="طول دیوار کشی",
            ),
        ),
    ]
