# Generated by Django 5.2 on 2025-09-06 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creator_project", "0005_project_site_area_project_wall_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.BinaryField(verbose_name="تصویر")),
                (
                    "image_mime_type",
                    models.CharField(default="image/jpeg", max_length=100),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="عنوان"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "upload_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ آپلود"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="creator_project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر گالری پروژه",
                "verbose_name_plural": "تصاویر گالری پروژه",
                "ordering": ["-upload_date"],
            },
        ),
    ]
