# Generated by Django 5.2.4 on 2026-09-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitysettings',
            name='brute_force_enabled',
            field=models.BooleanField(default=True, verbose_name='Brute Force Protection enabled'),
        ),
    ]
