# Generated by Django 5.2.4 on 2026-09-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_disable_brute_force_protection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitysettings',
            name='brute_force_enabled',
            field=models.BooleanField(default=True, verbose_name='Brute Force Protection enabled'),
        ),
    ]
