# Generated by Django 5.2 on 2025-06-04 22:39

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("CEO", "CEO"),
                            ("CHIEF_EXECUTIVE", "Chief Executive"),
                            ("VICE_CHIEF_EXECUTIVE", "Vice Chief Executive"),
                            ("EXPERT", "Expert"),
                            ("PROVINCE_MANAGER", "Province Manager"),
                        ],
                        default="PROVINCE_MANAGER",
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="province"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_pics/",
                        verbose_name="profile picture",
                    ),
                ),
                (
                    "نام",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="first name"
                    ),
                ),
                (
                    "نام_خانوادگی",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="last name"
                    ),
                ),
                (
                    "سمت",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="position"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExpertProvince",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("البرز", "البرز"),
                            ("آذربایجان شرقی", "آذربایجان شرقی"),
                            ("آذربایجان غربی", "آذربایجان غربی"),
                            ("بوشهر", "بوشهر"),
                            ("چهارمحال و بختیاری", "چهارمحال و بختیاری"),
                            ("فارس", "فارس"),
                            ("گیلان", "گیلان"),
                            ("گلستان", "گلستان"),
                            ("همدان", "همدان"),
                            ("هرمزگان", "هرمزگان"),
                            ("ایلام", "ایلام"),
                            ("اصفهان", "اصفهان"),
                            ("کرمان", "کرمان"),
                            ("کرمانشاه", "کرمانشاه"),
                            ("خراسان شمالی", "خراسان شمالی"),
                            ("خراسان رضوی", "خراسان رضوی"),
                            ("خراسان جنوبی", "خراسان جنوبی"),
                            ("خوزستان", "خوزستان"),
                            ("کهگیلویه و بویراحمد", "کهگیلویه و بویراحمد"),
                            ("کردستان", "کردستان"),
                            ("لرستان", "لرستان"),
                            ("مرکزی", "مرکزی"),
                            ("مازندران", "مازندران"),
                            ("قزوین", "قزوین"),
                            ("قم", "قم"),
                            ("سمنان", "سمنان"),
                            ("سیستان و بلوچستان", "سیستان و بلوچستان"),
                            ("تهران", "تهران"),
                            ("یزد", "یزد"),
                            ("زنجان", "زنجان"),
                            ("کیش", "کیش"),
                            ("اردبیل", "اردبیل"),
                        ],
                        max_length=50,
                        verbose_name="province",
                    ),
                ),
                (
                    "expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_provinces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expert Province Assignment",
                "verbose_name_plural": "Expert Province Assignments",
                "unique_together": {("expert", "province")},
            },
        ),
        migrations.CreateModel(
            name="UserProvince",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("البرز", "البرز"),
                            ("آذربایجان شرقی", "آذربایجان شرقی"),
                            ("آذربایجان غربی", "آذربایجان غربی"),
                            ("بوشهر", "بوشهر"),
                            ("چهارمحال و بختیاری", "چهارمحال و بختیاری"),
                            ("فارس", "فارس"),
                            ("گیلان", "گیلان"),
                            ("گلستان", "گلستان"),
                            ("همدان", "همدان"),
                            ("هرمزگان", "هرمزگان"),
                            ("ایلام", "ایلام"),
                            ("اصفهان", "اصفهان"),
                            ("کرمان", "کرمان"),
                            ("کرمانشاه", "کرمانشاه"),
                            ("خراسان شمالی", "خراسان شمالی"),
                            ("خراسان رضوی", "خراسان رضوی"),
                            ("خراسان جنوبی", "خراسان جنوبی"),
                            ("خوزستان", "خوزستان"),
                            ("کهگیلویه و بویراحمد", "کهگیلویه و بویراحمد"),
                            ("کردستان", "کردستان"),
                            ("لرستان", "لرستان"),
                            ("مرکزی", "مرکزی"),
                            ("مازندران", "مازندران"),
                            ("قزوین", "قزوین"),
                            ("قم", "قم"),
                            ("سمنان", "سمنان"),
                            ("سیستان و بلوچستان", "سیستان و بلوچستان"),
                            ("تهران", "تهران"),
                            ("یزد", "یزد"),
                            ("زنجان", "زنجان"),
                            ("کیش", "کیش"),
                            ("اردبیل", "اردبیل"),

                        ],
                        max_length=50,
                        verbose_name="province",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_provinces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Province Assignment",
                "verbose_name_plural": "User Province Assignments",
                "unique_together": {("user", "province")},
            },
        ),
    ]
