# Generated by Django 5.2 on 2025-06-04 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("creator_project", "0001_initial"),
        ("creator_subproject", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectFinancialAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=12)),
                ("allocation_date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_allocations",
                        to="creator_project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "تخصیص مالی پروژه",
                "verbose_name_plural": "تخصیص\u200cهای مالی پروژه",
                "ordering": ["-allocation_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("financial", "گزارش مالی"),
                            ("progress", "گزارش پیشرفت"),
                            ("issues", "گزارش مشکلات"),
                            ("summary", "گزارش خلاصه"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="creator_project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "گزارش پروژه",
                "verbose_name_plural": "گزارش\u200cهای پروژه",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.CharField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("from_date", models.DateField(blank=True, null=True)),
                ("to_date", models.DateField(blank=True, null=True)),
                (
                    "field_filter",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("all", "همه"),
                            ("project", "پروژه"),
                            ("subproject", "زیرپروژه"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("results_count", models.IntegerField(default=0)),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="All search filters in JSON format",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تاریخچه جستجو",
                "verbose_name_plural": "تاریخچه\u200cهای جستجو",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SubProjectReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("financial", "گزارش مالی"),
                            ("progress", "گزارش پیشرفت"),
                            ("issues", "گزارش مشکلات"),
                            ("summary", "گزارش خلاصه"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_subproject_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subproject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="creator_subproject.subproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "گزارش زیرپروژه",
                "verbose_name_plural": "گزارش\u200cهای زیرپروژه",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("query_text", models.CharField(blank=True, max_length=255, null=True)),
                ("from_date", models.DateField(blank=True, null=True)),
                ("to_date", models.DateField(blank=True, null=True)),
                (
                    "search_filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Search filters used to generate this report",
                    ),
                ),
                (
                    "project_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_generated",
                        to="reporter.projectreport",
                    ),
                ),
                (
                    "subproject_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_generated",
                        to="reporter.subprojectreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "گزارش تولید شده از جستجو",
                "verbose_name_plural": "گزارش\u200cهای تولید شده از جستجو",
                "ordering": ["-created_at"],
            },
        ),
    ]
