# Generated by Django 5.2 on 2025-08-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchhistory",
            name="search_type",
            field=models.CharField(
                choices=[
                    ("all", "همه"),
                    ("project", "پروژه"),
                    ("subproject", "زیرپروژه"),
                    ("program", "طرح"),
                ],
                default="all",
                max_length=20,
            ),
        ),
    ]
