# Generated by Django 5.2 on 2025-08-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporter", "0002_alter_searchhistory_search_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchhistory",
            name="search_type",
            field=models.CharField(
                choices=[
                    ("all", "همه"),
                    ("project", "پروژه"),
                    ("subproject", "زیرپروژه"),
                ],
                default="all",
                max_length=20,
            ),
        ),
    ]
