"""
Django settings for project_dashboard project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Generate a strong secret key and store it in environment variables
SECRET_KEY = config('SECRET_KEY', default='#+x1$zg#=h*^ky!_lzq(=bfg4t7=-$@cm7ln@b(!t#nmb)ue^h')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='projecthelal.rcs.ir,www.projecthelal.rcs.ir,localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    
    # Third-party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'jalali_date',
    
    # Custom apps
    'accounts',
    'dashboard',
    'creator_program',  # New app for Program management
    'creator_project',
    'creator_subproject',
    'creator_review',
    'reporter',
    'notifications',
    'notifications_sms',
    'webhooks',
    'activity_monitor',  # Activity monitoring and logging
    'session_manager',  # Session management and expiry
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
    # Brute Force Protection Middleware (MUST be before LoginRequiredMiddleware)
    "accounts.brute_force_middleware.BruteForceProtectionMiddleware",
    
    "project_dashboard.middleware.LoginRequiredMiddleware",
    
    # Activity monitoring middleware
    "activity_monitor.middleware.ActivityTrackingMiddleware",
    "activity_monitor.middleware.LoginLogoutMiddleware",
    "activity_monitor.middleware.ProjectChangeMiddleware",
    "activity_monitor.middleware.SecurityMiddleware",
    
    # Session management middleware (TEMPORARILY DISABLED FOR LOGIN TESTING)
    # "session_manager.middleware.SessionExpiryMiddleware",
    # "session_manager.middleware.SessionLoggingMiddleware",
    # "session_manager.security_middleware.SessionSecurityMiddleware",
]

ROOT_URLCONF = "project_dashboard.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project_dashboard.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database Configuration - Use environment variables for security
DATABASES = {
    "default": {
        "ENGINE": config('DB_ENGINE', default="django.db.backends.mysql"),
        "NAME": config('DB_NAME', default="project_manager_db"),
        "USER": config('DB_USER', default="root"),
        "PASSWORD": config('DB_PASSWORD', default=""),
        "HOST": config('DB_HOST', default="localhost"),
        "PORT": config('DB_PORT', default="3306"),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'use_unicode': True,
            'init_command': "SET NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'",
            'sql_mode': 'STRICT_TRANS_TABLES',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
# (Password validators are defined in the security section above)


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Tehran"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Crispy Forms settings
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# Authentication settings
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = 'dashboard:dashboard'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 3600  # 1 hour (3600 seconds)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)  # False for HTTP, True for HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Session expires when browser is closed
SESSION_SAVE_EVERY_REQUEST = True

# Session Security Settings
SESSION_MAX_FAILED_ATTEMPTS = 5
SESSION_LOCKOUT_DURATION = 300  # 5 minutes
SESSION_SECURE_COOKIES = config('SESSION_SECURE_COOKIES', default=False, cast=bool)  # False for HTTP, True for HTTPS
SESSION_CSRF_COOKIE_SECURE = config('SESSION_CSRF_COOKIE_SECURE', default=False, cast=bool)  # False for HTTP, True for HTTPS
SESSION_CSRF_COOKIE_HTTPONLY = True
SESSION_CSRF_COOKIE_SAMESITE = 'Lax'

# Jalali Date configuration
JALALI_DATE_DEFAULTS = {
    'LIST_DISPLAY_AUTO_CONVERT': True,
    'Strftime': {
        'date': '%y/%m/%d',
        'datetime': '%H:%M:%S _ %y/%m/%d',
    },
    'Static': {
        'js': [
            'admin/js/django_jalali.min.js',
        ],
        'css': {
            'all': [
              'admin/css/django_jalali.min.css',
            ]
        }
    },
}

# Set Persian/Farsi locale
import locale
import sys

# Ensure proper Unicode handling
import sys
import locale

# Set UTF-8 as the default encoding for the entire application
if sys.version_info[0] >= 3:
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8')

# Set locale to support UTF-8
try:
    locale.setlocale(locale.LC_ALL, 'fa_IR.UTF-8')
except locale.Error:
    try:
        locale.setlocale(locale.LC_ALL, 'Persian_Iran.UTF-8')
    except locale.Error:
        # Fallback to default locale
        locale.setlocale(locale.LC_ALL, '')

# Production Security Settings
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)  # Set to True when using HTTPS
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000  # 1 year (only when using HTTPS)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Additional Security Headers
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'

# CSRF Protection
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)  # True for HTTPS
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='').split(',') if config('CSRF_TRUSTED_ORIGINS', default='') else []

# Content Security Policy (CSP) - Basic protection
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net", "https://cdnjs.cloudflare.com")
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net", "https://cdnjs.cloudflare.com")
CSP_IMG_SRC = ("'self'", "data:", "https:")
CSP_FONT_SRC = ("'self'", "https://cdnjs.cloudflare.com")
CSP_CONNECT_SRC = ("'self'",)

# File Upload Security
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Password Security
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,
        }
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Brute Force Protection Settings
BRUTE_FORCE_MAX_ATTEMPTS_PER_IP = 10  # Maximum failed attempts per IP
BRUTE_FORCE_MAX_ATTEMPTS_PER_USER = 5  # Maximum failed attempts per user
BRUTE_FORCE_LOCKOUT_DURATION = 900  # Lockout duration in seconds (15 minutes)
BRUTE_FORCE_PROGRESSIVE_DELAY_BASE = 2  # Base delay in seconds
BRUTE_FORCE_CAPTCHA_THRESHOLD = 3  # Show CAPTCHA after this many failed attempts

# CAPTCHA Settings
CAPTCHA_CACHE_TIMEOUT = 300  # CAPTCHA expiration time in seconds (5 minutes)

# Windows VPS Static Files Configuration
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Windows VPS Media Files Configuration
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

LOGGING = {
    'version': 1,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',     # or DEBUG to see more
            'propagate': True,
        },
        'creator_program': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Add these settings to ensure proper Unicode handling
DEFAULT_CHARSET = 'utf-8'
FILE_CHARSET = 'utf-8'


