# Generated by Django 5.2.4 on 2026-08-17 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('status', models.CharField(default='success', max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'گزارش امنیتی دستیار',
                'verbose_name_plural': 'گزارش\u200cهای امنیتی دستیار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='گفتگوی جدید', max_length=200, verbose_name='عنوان')),
                ('context_type', models.CharField(blank=True, default='', max_length=30)),
                ('context_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گفتگوی دستیار',
                'verbose_name_plural': 'گفتگوهای دستیار',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'کاربر'), ('assistant', 'دستیار'), ('tool', 'ابزار')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.aiconversation', verbose_name='گفتگو')),
            ],
            options={
                'verbose_name': 'پیام دستیار',
                'verbose_name_plural': 'پیام\u200cهای دستیار',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUserPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='فعال')),
                ('daily_message_limit', models.PositiveIntegerField(default=30, verbose_name='سقف پیام روزانه')),
                ('monthly_message_limit', models.PositiveIntegerField(default=500, verbose_name='سقف پیام ماهانه')),
                ('allow_web_search', models.BooleanField(default=True, verbose_name='اجازه جستجوی وب')),
                ('allow_write_actions', models.BooleanField(default=False, verbose_name='اجازه عملیات تغییردهنده')),
                ('api_key', models.CharField(blank=True, default='', max_length=500, verbose_name='کلید API اختصاصی')),
                ('model_name', models.CharField(blank=True, default='', max_length=100, verbose_name='مدل')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_policy', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سیاست دستیار کاربر',
                'verbose_name_plural': 'سیاست\u200cهای دستیار کاربران',
            },
        ),
    ]
