# Generated by Django 5.2.4 on 2026-09-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_agent_layers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiautomationrule',
            options={'ordering': ['-created_at'], 'verbose_name': 'قاعده خودکارسازی AI', 'verbose_name_plural': 'قواعد خودکارسازی AI'},
        ),
        migrations.AlterModelOptions(
            name='aiexpertcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظر کارشناسی AI', 'verbose_name_plural': 'نظرات کارشناسی AI'},
        ),
        migrations.AlterModelOptions(
            name='aiknowledgeentry',
            options={'ordering': ['-priority', 'title'], 'verbose_name': 'دانش دستیار', 'verbose_name_plural': 'دانش دستیار'},
        ),
    ]
