# Generated by Django 5.2 on 2025-08-18 03:41

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityDashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("total_activities", models.PositiveIntegerField(default=0)),
                ("total_logins", models.PositiveIntegerField(default=0)),
                ("total_project_changes", models.PositiveIntegerField(default=0)),
                ("total_system_events", models.PositiveIntegerField(default=0)),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("new_users", models.PositiveIntegerField(default=0)),
                ("projects_created", models.PositiveIntegerField(default=0)),
                ("projects_updated", models.PositiveIntegerField(default=0)),
                ("projects_approved", models.PositiveIntegerField(default=0)),
                ("projects_rejected", models.PositiveIntegerField(default=0)),
                ("errors_count", models.PositiveIntegerField(default=0)),
                ("warnings_count", models.PositiveIntegerField(default=0)),
                ("avg_response_time", models.FloatField(default=0.0)),
                ("peak_concurrent_users", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("login_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("page_views", models.PositiveIntegerField(default=0)),
                (
                    "last_activity",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-login_time"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("VIEW", "View"),
                            ("DOWNLOAD", "Download"),
                            ("UPLOAD", "Upload"),
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("SUBMIT", "Submit"),
                            ("ASSIGN", "Assign"),
                            ("COMMENT", "Comment"),
                            ("NOTIFICATION", "Notification"),
                            ("SYSTEM", "System Event"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("is_system_event", models.BooleanField(default=False)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="activity_mo_timesta_136b0f_idx"
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="activity_mo_user_id_5a0a60_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "timestamp"],
                        name="activity_mo_activit_1c7e8b_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="activity_mo_content_8a4478_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("operation", models.CharField(max_length=50)),
                ("resource_type", models.CharField(max_length=50)),
                ("resource_id", models.CharField(max_length=50)),
                (
                    "before_state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "after_state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("session_id", models.CharField(blank=True, max_length=40)),
                ("requires_approval", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["operation", "timestamp"],
                        name="activity_mo_operati_0749e4_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="activity_mo_resourc_6ab042_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="activity_mo_user_id_ececae_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectChangeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("project_id", models.CharField(db_index=True, max_length=50)),
                ("project_name", models.CharField(max_length=255)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("STATUS", "Status Change"),
                            ("FINANCIAL", "Financial Change"),
                            ("PROGRESS", "Progress Update"),
                            ("ASSIGNMENT", "Assignment Change"),
                            ("REVIEW", "Review Update"),
                            ("FUNDING", "Funding Change"),
                            ("DOCUMENT", "Document Change"),
                            ("METADATA", "Metadata Change"),
                        ],
                        max_length=20,
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=100)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("change_description", models.TextField()),
                ("related_object_type", models.CharField(blank=True, max_length=50)),
                ("related_object_id", models.CharField(blank=True, max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["project_id", "timestamp"],
                        name="activity_mo_project_435229_idx",
                    ),
                    models.Index(
                        fields=["change_type", "timestamp"],
                        name="activity_mo_change__ec2706_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="activity_mo_user_id_ea102a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ERROR", "Error"),
                            ("WARNING", "Warning"),
                            ("INFO", "Information"),
                            ("SECURITY", "Security Event"),
                            ("PERFORMANCE", "Performance Issue"),
                            ("BACKUP", "Backup Event"),
                            ("MAINTENANCE", "Maintenance Event"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("stack_trace", models.TextField(blank=True)),
                ("component", models.CharField(blank=True, max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="activity_mo_event_t_112d6e_idx",
                    ),
                    models.Index(
                        fields=["severity", "timestamp"],
                        name="activity_mo_severit_d4c80a_idx",
                    ),
                    models.Index(
                        fields=["is_resolved", "timestamp"],
                        name="activity_mo_is_reso_2820b8_idx",
                    ),
                ],
            },
        ),
    ]
