# Generated by Django 5.2 on 2025-08-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_monitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectchangelog",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("STATUS", "Status Change"),
                    ("FINANCIAL", "Financial Change"),
                    ("PROGRESS", "Progress Update"),
                    ("ASSIGNMENT", "Assignment Change"),
                    ("REVIEW", "Review Update"),
                    ("FUNDING", "Funding Change"),
                    ("DOCUMENT", "Document Change"),
                    ("METADATA", "Metadata Change"),
                ],
                max_length=20,
            ),
        ),
    ]
