# Generated by Django 5.2 on 2025-08-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_monitor", "0002_alter_projectchangelog_change_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectchangelog",
            name="original_field_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
