# Generated by Django 5.2 on 2025-09-06 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_monitor", "0003_projectchangelog_original_field_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GallerySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_images_per_page",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="تعداد تصاویری که در هر صفحه گالری نمایش داده می\u200cشود",
                        verbose_name="حداکثر تعداد تصاویر در هر صفحه",
                    ),
                ),
                (
                    "max_image_size_mb",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="حداکثر حجم مجاز برای هر تصویر در مگابایت",
                        verbose_name="حداکثر حجم تصویر (مگابایت)",
                    ),
                ),
                (
                    "thumbnail_size",
                    models.PositiveIntegerField(
                        default=200,
                        help_text="اندازه تصاویر کوچک در پیکسل",
                        verbose_name="اندازه تصاویر کوچک (پیکسل)",
                    ),
                ),
                (
                    "enable_image_compression",
                    models.BooleanField(
                        default=True,
                        help_text="تصاویر به صورت خودکار فشرده می\u200cشوند",
                        verbose_name="فشرده\u200cسازی خودکار تصاویر",
                    ),
                ),
                (
                    "allowed_image_formats",
                    models.JSONField(
                        default=list,
                        help_text="لیست فرمت\u200cهای مجاز برای آپلود تصاویر",
                        verbose_name="فرمت\u200cهای مجاز تصاویر",
                    ),
                ),
                (
                    "show_image_titles",
                    models.BooleanField(
                        default=True,
                        help_text="عنوان تصاویر در گالری نمایش داده می\u200cشود",
                        verbose_name="نمایش عنوان تصاویر",
                    ),
                ),
                (
                    "show_image_descriptions",
                    models.BooleanField(
                        default=True,
                        help_text="توضیحات تصاویر در گالری نمایش داده می\u200cشود",
                        verbose_name="نمایش توضیحات تصاویر",
                    ),
                ),
                (
                    "show_upload_dates",
                    models.BooleanField(
                        default=True,
                        help_text="تاریخ آپلود تصاویر نمایش داده می\u200cشود",
                        verbose_name="نمایش تاریخ آپلود",
                    ),
                ),
                (
                    "images_per_row",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="تعداد تصاویری که در هر ردیف نمایش داده می\u200cشود",
                        verbose_name="تعداد تصاویر در هر ردیف",
                    ),
                ),
                (
                    "enable_lightbox",
                    models.BooleanField(
                        default=True,
                        help_text="امکان نمایش تصاویر در اندازه بزرگ فعال است",
                        verbose_name="فعال\u200cسازی نمایش بزرگ تصاویر",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="آخرین بروزرسانی توسط",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات گالری",
                "verbose_name_plural": "تنظیمات گالری",
            },
        ),
    ]
