# Generated by Django 5.2 on 2025-09-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_monitor", "0004_add_gallery_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallerysettings",
            name="allowed_image_formats",
        ),
        migrations.RemoveField(
            model_name="gallerysettings",
            name="enable_lightbox",
        ),
        migrations.RemoveField(
            model_name="gallerysettings",
            name="images_per_row",
        ),
        migrations.RemoveField(
            model_name="gallerysettings",
            name="show_image_descriptions",
        ),
        migrations.RemoveField(
            model_name="gallerysettings",
            name="show_image_titles",
        ),
        migrations.RemoveField(
            model_name="gallerysettings",
            name="show_upload_dates",
        ),
        migrations.RemoveField(
            model_name="gallerysettings",
            name="thumbnail_size",
        ),
        migrations.AddField(
            model_name="gallerysettings",
            name="max_total_size_mb",
            field=models.PositiveIntegerField(
                default=500,
                help_text="حداکثر حجم کل تصاویر یک پروژه در مگابایت",
                verbose_name="حداکثر حجم کل تصاویر (مگابایت)",
            ),
        ),
        migrations.AddField(
            model_name="gallerysettings",
            name="max_upload_images",
            field=models.PositiveIntegerField(
                default=100,
                help_text="حداکثر تعداد تصاویری که می\u200cتوان در یک پروژه آپلود کرد",
                verbose_name="حداکثر تعداد تصاویر قابل آپلود",
            ),
        ),
        migrations.AlterField(
            model_name="gallerysettings",
            name="max_image_size_mb",
            field=models.PositiveIntegerField(
                default=5,
                help_text="حداکثر حجم مجاز برای هر تصویر در مگابایت",
                verbose_name="حداکثر حجم هر تصویر (مگابایت)",
            ),
        ),
    ]
