# Generated by Django 5.2 on 2025-06-04 22:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("creator_project", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("advance_payment", "پیش پرداخت"),
                            ("temporary_report", "صورت وضعیت موقت"),
                            ("permanent_report", "صورت وضعیت دائم"),
                            ("adjustment_report", "صورت وضعیت تعدیل"),
                        ],
                        max_length=20,
                        verbose_name="نوع سند مالی",
                    ),
                ),
                (
                    "document_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="شماره سند مالی"
                    ),
                ),
                (
                    "contractor_amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=14,
                        verbose_name="مبلغ ناخالص پیمان کار",
                    ),
                ),
                (
                    "contractor_date",
                    models.DateField(verbose_name="تاریخ ارسال سند مالی پیمان کار"),
                ),
                (
                    "contractor_submit_date",
                    models.DateField(verbose_name="تاریخ ارسال سند مالی پیمان کار"),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=14,
                        verbose_name="مبلغ ناخالص تایید شده",
                    ),
                ),
                (
                    "approval_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ تایید سند مالی"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_financial_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_documents",
                        to="creator_subproject.financialdocument",
                        verbose_name="ارتباط با سند مالی",
                    ),
                ),
            ],
            options={
                "verbose_name": "سند مالی",
                "verbose_name_plural": "اسناد مالی",
                "ordering": ["document_type", "document_number"],
            },
        ),
        migrations.CreateModel(
            name="DocumentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.BinaryField(verbose_name="فایل"),
                ),
                (
                    "file_mime_type",
                    models.CharField(max_length=100, default='application/octet-stream', verbose_name="نوع فایل (MIME)"),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="نام فایل")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="creator_subproject.financialdocument",
                    ),
                ),
            ],
            options={
                "db_table": "creator_subproject_documentfile",
            },
        ),
        migrations.CreateModel(
            name="ProjectSituation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "situation_type",
                    models.CharField(
                        choices=[
                            ("مالی", "مالی"),
                            ("فیزیکی", "فیزیکی"),
                            ("حقوقی", "حقوقی"),
                            ("فنی", "فنی"),
                        ],
                        max_length=50,
                        verbose_name="نوع وضعیت",
                    ),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                ("report_date", models.DateField(verbose_name="تاریخ گزارش")),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="حل شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_situations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="situations",
                        to="creator_project.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "وضعیت پروژه",
                "verbose_name_plural": "وضعیت های پروژه",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="SubProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="نام زیرپروژه",
                    ),
                ),
                (
                    "sub_project_type",
                    models.CharField(
                        choices=[
                            ("احداث", "احداث"),
                            ("تکمیل", "تکمیل"),
                            ("محوطه سازی", "محوطه سازی"),
                            ("دیوار کشی", "دیوار کشی"),
                            ("محوطه سازی و دیوار کشی", "محوطه سازی و دیوار کشی"),
                            ("تعمیرات", "تعمیرات"),
                            ("مشاور فاز یک و دو (طراحی)", "مشاور فاز یک و دو (طراحی)"),
                            ("مشاور فاز سه (نظارت)", "مشاور فاز سه (نظارت)"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "sub_project_number",
                    models.PositiveSmallIntegerField(help_text="Must be between 1-5"),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ شروع زیر پروژه"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ پایان زیر پروژه"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("فعال", "فعال"),
                            ("غیرفعال-ختم پیمان", "غیرفعال-ختم پیمان"),
                            ("غیر فعال- ماده 46", "غیر فعال- ماده 46"),
                            ("غیره فعال-تعلیق", "غیره فعال-تعلیق"),
                            ("غیره فعال-اتمام قرار داد", "غیره فعال-اتمام قرار داد"),
                            ("تحویل موقت", "تحویل موقت"),
                            ("تحویل قطعی", "تحویل قطعی"),
                            ("تامین اعتبار", "تامین اعتبار"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "physical_progress",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=5, null=True
                    ),
                ),
                (
                    "executive_stage",
                    models.CharField(
                        choices=[
                            ("فاز مطالعاتی", "فاز مطالعاتی"),
                            ("طراحی نقشه های فاز 1و2", "طراحی نقشه های فاز 1و2"),
                            ("برگزاری مناقصه", "برگزاری مناقصه"),
                            (
                                "انعقاد قرار داد و تحویل زمین",
                                "انعقاد قرار داد و تحویل زمین",
                            ),
                            ("تجهیزات کارگاهی", "تجهیزات کارگاهی"),
                            ("گودبرداری", "گودبرداری"),
                            ("فونداسیون", "فونداسیون"),
                            ("اسکلت", "اسکلت"),
                            ("سفت کاری", "سفت کاری"),
                            ("نما", "نما"),
                            ("اجرای تاسیسات", "اجرای تاسیسات"),
                            ("نازک کاری", "نازک کاری"),
                            (
                                "اجرای نصبیات برقی و مکانیکی",
                                "اجرای نصبیات برقی و مکانیکی",
                            ),
                            ("محوطه سازی", "محوطه سازی"),
                            ("دیوارکشی", "دیوارکشی"),
                            ("محوطه سازی و دیوار کشی", "محوطه سازی و دیوار کشی"),
                        ],
                        max_length=100,
                    ),
                ),
                ("remaining_work", models.TextField(blank=True, null=True)),
                (
                    "is_suportting_charity",
                    models.CharField(
                        choices=[("دارد", "دارد"), ("ندارد", "ندارد")],
                        default="ندارد",
                        max_length=25,
                        verbose_name="مشارکت خیرین",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("شروع با", "شروع با"),
                            ("پایان با", "پایان با"),
                            ("بعد از", "بعد از"),
                            ("قبل از", "قبل از"),
                            ("شناور", "شناور"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="نوع ارتباط",
                    ),
                ),
                (
                    "relationship_delay",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="تعجیل وتاخیر ارتباط زیر پروژه",
                    ),
                ),
                (
                    "imagenary_duration",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="مدت تخمینی (روز)"
                    ),
                ),
                (
                    "imagenrary_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="هزینه تخمینی (ریال)",
                    ),
                ),
                (
                    "cost_calculation_method",
                    models.TextField(
                        blank=True, null=True, verbose_name="روش محاسبه هزینه تقریبی"
                    ),
                ),
                (
                    "has_adjustment",
                    models.CharField(
                        choices=[("دارد", "دارد"), ("ندارد", "ندارد")],
                        default="ندارد",
                        max_length=10,
                        verbose_name="افزایش 25 درصدی قرار داد",
                    ),
                ),
                (
                    "adjustment_coefficient",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="درصد افزایش مبلغ قرار داد",
                    ),
                ),
                (
                    "has_25_percent_increase",
                    models.CharField(
                        choices=[("دارد", "دارد"), ("ندارد", "ندارد")],
                        default="ندارد",
                        max_length=10,
                        verbose_name="25 درصد افزایش پیمان",
                    ),
                ),
                (
                    "increase_coefficient_25_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=1.0,
                        max_digits=10,
                        null=True,
                        verbose_name="ضریب 25 درصد افزایش پیمان",
                    ),
                ),
                ("contract_start_date", models.DateField(blank=True, null=True)),
                ("contract_end_date", models.DateField(blank=True, null=True)),
                (
                    "contract_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="مبلغ قرارداد ( ریال)",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("سرجمع", "سرجمع"),
                            ("فرست بها", "فرست بها"),
                            ("پیمان مدیریت", "پیمان مدیریت"),
                            ("مشارکت در ساخت", "مشارکت در ساخت"),
                            ("خیر ساز", "خیر ساز"),
                            ("BOT", "BOT"),
                            ("EPC", "EPC"),
                            ("EC", "EC"),
                            ("امانی", "امانی"),
                            ("فاقد قرارداد", "فاقد قرارداد"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "execution_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("مناقصه عمومی- سه عاملی", "مناقصه عمومی- سه عاملی"),
                            ("ترک تشریفات -سه عاملی", "ترک تشریفات -سه عاملی"),
                            ("مناقصه محدود-سه عاملی", "مناقصه محدود-سه عاملی"),
                            (
                                "مناقصه عمومی نظارت دفترفنی استان",
                                "مناقصه عمومی نظارت دفترفنی استان",
                            ),
                            (
                                "ترک تشریفات نظارت دفترفنی استان",
                                "ترک تشریفات نظارت دفترفنی استان",
                            ),
                            (
                                "مناقصه محدود نظارت دفترفنی استان",
                                "مناقصه محدود نظارت دفترفنی استان",
                            ),
                            (
                                "استعلام بها نظارت دفترفنی استان",
                                "استعلام بها نظارت دفترفنی استان",
                            ),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "contractor_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="نام پیمانکار",
                    ),
                ),
                (
                    "contractor_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="شناسه پیمانکار",
                    ),
                ),
                (
                    "total_prepayments",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="جمع مبلغ های پیش پرداخت",
                    ),
                ),
                (
                    "situation_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="مبلغ صورت وضعیت",
                    ),
                ),
                (
                    "total_adjustment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="جمع مبلغ صورت وضعیت تعدیل",
                    ),
                ),
                (
                    "predicted_adjustment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="مجموع مبلغ پیشبینی شده ی تعدیل های تا انتهای پروژه",
                    ),
                ),
                (
                    "subproject_debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="دیون زیرپروژه",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_threshold",
                    models.CharField(
                        choices=[
                            ("کوچک", "کوچک"),
                            ("متوسط", "متوسط"),
                            ("بزرگ", "بزرگ"),
                        ],
                        default="کوچک",
                        max_length=10,
                        verbose_name="نصاب معاملات",
                    ),
                ),
                (
                    "tender_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("عمومی-یک مرحله ای", "عمومی-یک مرحله ای"),
                            ("عمومی- دومرحله ای", "عمومی- دومرحله ای"),
                            ("ترک تشریفات", "ترک تشریفات"),
                            ("استعلام بهای متوسط", "استعلام بهای متوسط"),
                            ("معامله بر خط", "معامله بر خط"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="نوع مناقصه",
                    ),
                ),
                (
                    "has_consultant",
                    models.CharField(
                        choices=[("دارد", "دارد"), ("ندارد", "ندارد")],
                        default="ندارد",
                        max_length=10,
                        verbose_name="مشاور",
                    ),
                ),
                (
                    "consultant_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="نام مشاور"
                    ),
                ),
                (
                    "consultant_national_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="شناسه ملی مشاور",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_subprojects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subprojects",
                        to="creator_project.project",
                    ),
                ),
                (
                    "related_subproject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_subprojects",
                        to="creator_subproject.subproject",
                        verbose_name="ارتباط زیر پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "زیرپروژه",
                "verbose_name_plural": "زیرپروژه\u200cها",
                "ordering": ["project", "sub_project_number"],
            },
        ),
        migrations.CreateModel(
            name="SituationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="شماره صورت وضعیت"
                    ),
                ),
                (
                    "allocation_type",
                    models.CharField(
                        choices=[("موقت", "موقت"), ("دائم", "دائم")],
                        max_length=50,
                        verbose_name="نوع صورت وضعیت",
                    ),
                ),
                ("allocation_date", models.DateField(verbose_name="تاریخ صورت وضعیت")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "payment_amount_field",
                    models.BigIntegerField(verbose_name="مبلغ پرداختی"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "subproject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="situation_reports",
                        to="creator_subproject.subproject",
                        verbose_name="زیرپروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورت وضعیت ها کارکرد",
                "verbose_name_plural": "صورت وضعیت\u200cها کارکرد",
                "ordering": ["-allocation_date"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=14, verbose_name="مبلغ پرداخت شده"
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="تاریخ پرداختی")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="creator_subproject.financialdocument",
                        verbose_name="سند مالی مرتبط",
                    ),
                ),
                (
                    "subproject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="creator_subproject.subproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداختی",
                "verbose_name_plural": "پرداختی ها",
                "ordering": ["payment_date"],
            },
        ),
        migrations.AddField(
            model_name="financialdocument",
            name="subproject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_documents",
                to="creator_subproject.subproject",
            ),
        ),
        migrations.CreateModel(
            name="AdjustmentSituationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="شماره صورت وضعیت تعدیل"
                    ),
                ),
                (
                    "allocation_date",
                    models.DateField(verbose_name="تاریخ صورت وضعیت تعدیل"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "payment_amount_field",
                    models.BigIntegerField(verbose_name="مبلغ پرداختی تعدیل"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "subproject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustment_situation_reports",
                        to="creator_subproject.subproject",
                        verbose_name="زیرپروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورت وضعیت ها تعدیل",
                "verbose_name_plural": "صورت وضعیت\u200cها تعدیل",
                "ordering": ["-allocation_date"],
            },
        ),
        migrations.CreateModel(
            name="SubProjectGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.BinaryField(verbose_name="تصویر"),
                ),
                (
                    "image_mime_type",
                    models.CharField(max_length=100, default='image/jpeg'),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="عنوان"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "upload_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ آپلود"),
                ),
                (
                    "subproject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="creator_subproject.subproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر گالری زیرپروژه",
                "verbose_name_plural": "تصاویر گالری زیرپروژه",
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="SubProjectRejectionComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subproject_rejection_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subproject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rejection_comments",
                        to="creator_subproject.subproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "نظر رد زیرپروژه",
                "verbose_name_plural": "نظرات رد زیرپروژه",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubProjectUpdateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("field_name", models.CharField(max_length=50)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                (
                    "subproject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_history",
                        to="creator_subproject.subproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subproject_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تاریخچه بروزرسانی زیرپروژه",
                "verbose_name_plural": "تاریخچه بروزرسانی زیرپروژه\u200cها",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="financialdocument",
            unique_together={("subproject", "document_type", "document_number")},
        ),
    ]
