# Generated by Django 5.2.4 on 2025-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_subproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='file_mime_type',
            field=models.CharField(default='application/octet-stream', max_length=100, verbose_name='نوع فایل (MIME)'),
        ),
    ] 