# Generated by Django 5.2.4 on 2025-07-28
# This migration was recreated to fix the duplicate column issue
# The file_mime_type column already exists in the database from the initial migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_subproject', '0001_initial'),
    ]

    operations = [
        # This operation is skipped if the column already exists
        # The column was already added in the initial migration
        migrations.AddField(
            model_name='documentfile',
            name='file_mime_type',
            field=models.CharField(default='application/octet-stream', max_length=100, verbose_name='نوع فایل (MIME)'),
        ),
    ] 