# Generated by Django 5.2.4 on 2025-07-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_subproject', '0003_documentfile_file_mime_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproject',
            name='executive_stage',
        ),
        migrations.AlterField(
            model_name='subproject',
            name='sub_project_type',
            field=models.CharField(choices=[('فاز مطالعاتی', 'فاز مطالعاتی'), ('طراحی نقشه های فاز 1و2', 'طراحی نقشه های فاز 1و2'), ('برگزاری مناقصه', 'برگزاری مناقصه'), ('انعقاد قرار داد و تحویل زمین', 'انعقاد قرار داد و تحویل زمین'), ('تجهیزات کارگاهی', 'تجهیزات کارگاهی'), ('گودبرداری', 'گودبرداری'), ('فونداسیون', 'فونداسیون'), ('اسکلت', 'اسکلت'), ('سفت کاری', 'سفت کاری'), ('نما', 'نما'), ('اجرای تاسیسات', 'اجرای تاسیسات'), ('نازک کاری', 'نازک کاری'), ('اجرای نصبیات برقی و مکانیکی', 'اجرای نصبیات برقی و مکانیکی'), ('محوطه سازی', 'محوطه سازی'), ('دیوارکشی', 'دیوارکشی'), ('محوطه سازی و دیوار کشی', 'محوطه سازی و دیوار کشی')], max_length=100, verbose_name='نوع زیرپروژه'),
        ),
    ]
