# Generated by Django 5.2 on 2025-08-05 05:55

from django.db import migrations


def add_executive_stage_default(apps, schema_editor):
    """Add default value to executive_stage field if it still exists"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if executive_stage column exists
        cursor.execute("PRAGMA table_info(creator_subproject_subproject)")
        columns = cursor.fetchall()
        column_names = [col[1] for col in columns]
        
        if 'executive_stage' in column_names:
            # Add default value to existing records
            cursor.execute("""
                UPDATE creator_subproject_subproject 
                SET executive_stage = 'فاز مطالعاتی' 
                WHERE executive_stage IS NULL
            """)


def reverse_add_executive_stage_default(apps, schema_editor):
    """Reverse operation - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("creator_subproject", "0004_remove_executive_stage_field"),
    ]

    operations = [
        migrations.RunPython(
            add_executive_stage_default,
            reverse_add_executive_stage_default,
        ),
    ]
