# Generated by Django 5.2.4 on 2025-08-05 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("creator_subproject", "0004_remove_executive_stage_field"),
    ]

    operations = [
        # This migration replaces the problematic 0005_auto_20250805_0925.py
        # which was trying to access the executive_stage field that was already removed
        # No operations needed - this is just a placeholder to maintain migration sequence
    ] 