# Generated by Django 5.2 on 2025-08-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("creator_subproject", "0003_documentfile_file_mime_type"),
        ("creator_subproject", "0005_fix_executive_stage_migration"),
    ]

    operations = []
