# Generated by Django 5.2 on 2025-09-06 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("creator_subproject", "0006_merge_20250805_1122"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SubProjectGalleryImage",
        ),
    ]
