# Generated by Django 5.2.4 on 2026-08-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_subproject', '0010_rename_sub_project_type_to_project_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='has_tax_insurance_increase',
            field=models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], default='ندارد', max_length=10, verbose_name='افزایش مبلغ برای مالیات ارزش افزوده و بیمه'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='tax_insurance_increase_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='درصد افزایش قرارداد مالیات ارزش افزوده و بیمه'),
        ),
    ]
