# Generated by Django 5.2 on 2025-06-04 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Provider Name"),
                ),
                ("base_url", models.URLField(verbose_name="API Base URL")),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Username"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Password"
                    ),
                ),
                ("api_key", models.CharField(max_length=500, verbose_name="API Key")),
                (
                    "sender_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Sender Number",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Active"),
                ),
            ],
            options={
                "verbose_name": "SMS Provider",
                "verbose_name_plural": "SMS Providers",
            },
        ),
        migrations.CreateModel(
            name="SMSSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outdated_project_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Number of days after which a project is considered outdated if not updated",
                        verbose_name="Days Until Project Considered Outdated",
                    ),
                ),
                (
                    "not_examined_days",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Number of days after which to remind experts about unexamined projects",
                        verbose_name="Days Until Expert Reminder",
                    ),
                ),
                (
                    "auto_send_outdated",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically send SMS for outdated projects",
                        verbose_name="Auto Send Outdated Project Notifications",
                    ),
                ),
                (
                    "auto_send_rejected",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically send SMS for rejected projects",
                        verbose_name="Auto Send Rejected Project Notifications",
                    ),
                ),
                (
                    "auto_send_not_examined",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically send SMS for not examined projects",
                        verbose_name="Auto Send Not Examined Project Notifications",
                    ),
                ),
                (
                    "auto_send_funding_approved",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically send SMS for approved funding requests",
                        verbose_name="Auto Send Funding Approved Notifications",
                    ),
                ),
                (
                    "check_interval_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="How often to check for outdated/unexamined projects (in hours)",
                        verbose_name="Check Interval (Hours)",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications_sms.smsprovider",
                        verbose_name="SMS Provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Settings",
                "verbose_name_plural": "SMS Settings",
            },
        ),
        migrations.CreateModel(
            name="SMSTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Template Name"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PROJECT_OUTDATED", "Project Not Updated"),
                            ("PROJECT_REJECTED", "Project Rejected"),
                            ("PROJECT_NOT_EXAMINED", "Project Not Examined"),
                            ("FUNDING_REQUEST_APPROVED", "Funding Request Approved"),
                            ("CUSTOM", "Custom Message"),
                        ],
                        max_length=50,
                        verbose_name="Template Type",
                    ),
                ),
                ("content", models.TextField(verbose_name="Message Content")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Default Template"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Template",
                "verbose_name_plural": "SMS Templates",
            },
        ),
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_number",
                    models.CharField(max_length=20, verbose_name="Recipient Number"),
                ),
                ("message", models.TextField(verbose_name="Message Content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Message"
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Message ID"
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_sms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient User",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_sms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sender",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications_sms.smsprovider",
                        verbose_name="Provider Used",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications_sms.smstemplate",
                        verbose_name="Template Used",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Log",
                "verbose_name_plural": "SMS Logs",
                "ordering": ["-sent_at"],
            },
        ),
    ]
