# Generated by Django 5.2 on 2025-06-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications_sms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsprovider",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("IPPANEL", "IPPanel"),
                    ("FARAZSMS", "FarazSMS"),
                    ("CUSTOM", "Custom"),
                ],
                default="IPPANEL",
                max_length=50,
                verbose_name="Provider Type",
            ),
        ),
        migrations.AlterField(
            model_name="smsprovider",
            name="base_url",
            field=models.URLField(
                default="https://rest.ippanel.com/v1", verbose_name="API Base URL"
            ),
        ),
    ]
