# Generated by Django 5.2.4 on 2025-07-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_sms', '0002_smsprovider_provider_type_alter_smsprovider_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsprovider',
            name='base_url',
            field=models.URLField(default='https://api2.ippanel.com/api/v1', verbose_name='API Base URL'),
        ),
    ]
