# Generated by Django 5.2 on 2025-06-04 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("creator_project", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpertReminderSMSSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "reminder_days",
                    models.PositiveIntegerField(
                        default=3, verbose_name="روزهای تاخیر بررسی"
                    ),
                ),
                (
                    "message_template",
                    models.TextField(
                        default="با سلام وعرض ادب خدمت همکار گرامی لطفا به وضعیت پروژه {project_name} اقدام فرمایید",
                        verbose_name="قالب پیام",
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین اجرا"
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات پیامک یادآوری کارشناس",
                "verbose_name_plural": "تنظیمات پیامک یادآوری کارشناس",
            },
        ),
        migrations.CreateModel(
            name="RejectionSMSSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "message_template",
                    models.TextField(
                        default="با سلام وعرض ادب خدمت همکار گرامی به دلیل زیر پروژه نیازمند اصلاح است {rejection_reason}",
                        verbose_name="قالب پیام",
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین اجرا"
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات پیامک رد پروژه",
                "verbose_name_plural": "تنظیمات پیامک رد پروژه",
            },
        ),
        migrations.CreateModel(
            name="SMSSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "api_key",
                    models.CharField(
                        default="OWVlNWZlOWEtOTVhOC00YmM3LTliYWMtNTk0Y2Y1ZTg4MGI3NjU1NWNjMTgzMThmNWVkYmY3OWFjZWJjNzczNzI3N2I=",
                        max_length=255,
                        verbose_name="کلید API",
                    ),
                ),
                (
                    "sender_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="شماره فرستنده",
                    ),
                ),
                (
                    "inactivity_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="حداکثر روزهای عدم بروزرسانی"
                    ),
                ),
                (
                    "message_template",
                    models.TextField(
                        default="با سلام وعرض ادب خدمت همکار گرامی لطفا به بروزسانی وضعیت پروژه {project_name} اقدام فرمایید",
                        verbose_name="قالب پیام",
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین اجرا"
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات پیامک",
                "verbose_name_plural": "تنظیمات پیامک",
            },
        ),
        migrations.CreateModel(
            name="ProjectExpertNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("project_update", "بروزرسانی پروژه"),
                            ("project_rejection", "رد پروژه"),
                            ("expert_reminder", "یادآوری کارشناس"),
                        ],
                        default="project_update",
                        max_length=50,
                        verbose_name="نوع اطلاع\u200cرسانی",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="خوانده شده"),
                ),
                (
                    "notified_via_sms",
                    models.BooleanField(
                        default=False, verbose_name="اطلاع\u200cرسانی پیامکی"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, null=True, verbose_name="دلیل رد"),
                ),
                (
                    "expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کارشناس",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_notifications",
                        to="creator_project.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "اطلاع\u200cرسانی پروژه",
                "verbose_name_plural": "اطلاع\u200cرسانی\u200cهای پروژه",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="متن پیام")),
                (
                    "project_name",
                    models.CharField(max_length=255, verbose_name="نام پروژه"),
                ),
                (
                    "project_id",
                    models.CharField(max_length=50, verbose_name="شناسه پروژه"),
                ),
                ("province", models.CharField(max_length=50, verbose_name="استان")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ارسال"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("sent", "ارسال شده"),
                            ("delivered", "تحویل داده شده"),
                            ("failed", "خطا"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="شناسه پیام"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="پیام خطا"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="دریافت کننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "گزارش پیامک",
                "verbose_name_plural": "گزارش پیامک\u200cها",
                "ordering": ["-sent_at"],
            },
        ),
    ]
